# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile
config:
  partial_parse: True
  send_anonymous_usage_stats: False

default:
  target: dev
  outputs:
     dev:
       type: bigquery
       method: oauth
       project: "{{ env_var('PROJECT_ID') }}"
       location: "asia-northeast1"
       dataset: "test_yu_tokyo"
       priority: "{{ env_var('DBT_BIGQUERY_PRIORITY', 'interactive') }}"
       # If we want to increase concurrency, please change `threads`.
       threads: |
         {{ env_var("DBT_THREADS", 1) }}
